config/routes.rb
BootstrapRailsDemo::Application.routes.draw do
  resources :products

  get '/' => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product].permit(:name, :price))

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product].permit(:name, :price))
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.haml
!!!
%html
  %head
    %title Ruby on Rails: Welcome aboard
    %style{:media => "screen", :type => "text/css"}
      body {
      margin: 0;
      margin-bottom: 25px;
      padding: 0;
      background-color: #f0f0f0;
      font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
      font-size: 13px;
      color: #333;
      }
      
      h1 {
      font-size: 28px;
      color: #000;
      }
      
      a  {color: #03c}
      a:hover {
      background-color: #03c;
      color: white;
      text-decoration: none;
      }
      
      
      \#page {
      background-color: #f0f0f0;
      width: 750px;
      margin: 0;
      margin-left: auto;
      margin-right: auto;
      }
      
      \#content {
      float: left;
      background-color: white;
      border: 3px solid #aaa;
      border-top: none;
      padding: 25px;
      width: 500px;
      }
      
      \#sidebar {
      float: right;
      width: 175px;
      }
      
      \#footer {
      clear: both;
      }
      
      \#header, #about, #getting-started {
      padding-left: 75px;
      padding-right: 30px;
      }
      
      
      \#header {
      background-image: url("assets/rails.png");
      background-repeat: no-repeat;
      background-position: top left;
      height: 64px;
      }
      \#header h1, #header h2 {margin: 0}
      \#header h2 {
      color: #888;
      font-weight: normal;
      font-size: 16px;
      }
      
      
      \#about h3 {
      margin: 0;
      margin-bottom: 10px;
      font-size: 14px;
      }
      
      \#about-content {
      background-color: #ffd;
      border: 1px solid #fc0;
      margin-left: -55px;
      margin-right: -10px;
      }
      \#about-content table {
      margin-top: 10px;
      margin-bottom: 10px;
      font-size: 11px;
      border-collapse: collapse;
      }
      \#about-content td {
      padding: 10px;
      padding-top: 3px;
      padding-bottom: 3px;
      }
      \#about-content td.name  {color: #555}
      \#about-content td.value {color: #000}
      
      \#about-content ul {
      padding: 0;
      list-style-type: none;
      }
      
      \#about-content.failure {
      background-color: #fcc;
      border: 1px solid #f00;
      }
      \#about-content.failure p {
      margin: 0;
      padding: 10px;
      }
      
      
      \#getting-started {
      border-top: 1px solid #ccc;
      margin-top: 25px;
      padding-top: 15px;
      }
      \#getting-started h1 {
      margin: 0;
      font-size: 20px;
      }
      \#getting-started h2 {
      margin: 0;
      font-size: 14px;
      font-weight: normal;
      color: #333;
      margin-bottom: 25px;
      }
      \#getting-started ol {
      margin-left: 0;
      padding-left: 0;
      }
      \#getting-started li {
      font-size: 18px;
      color: #888;
      margin-bottom: 25px;
      }
      \#getting-started li h2 {
      margin: 0;
      font-weight: normal;
      font-size: 18px;
      color: #333;
      }
      \#getting-started li p {
      color: #555;
      font-size: 13px;
      }
      
      
      \#sidebar ul {
      margin-left: 0;
      padding-left: 0;
      }
      \#sidebar ul h3 {
      margin-top: 25px;
      font-size: 16px;
      padding-bottom: 10px;
      border-bottom: 1px solid #ccc;
      }
      \#sidebar li {
      list-style-type: none;
      }
      \#sidebar ul.links li {
      margin-bottom: 5px;
      }
      
      \.filename {
      font-style: italic;
      }
    :javascript
      function about() {
        info = document.getElementById('about-content');
        if (window.XMLHttpRequest)
          { xhr = new XMLHttpRequest(); }
        else
          { xhr = new ActiveXObject("Microsoft.XMLHTTP"); }
        xhr.open("GET","rails/info/properties",false);
        xhr.send("");
        info.innerHTML = xhr.responseText;
        info.style.display = 'block'
      }
      %body
    #page
      #sidebar
        %ul#sidebar-items
          %li
            %h3 Browse the documentation
            %ul.links
              %li
                %a{:href => "http://guides.rubyonrails.org/"} Rails Guides
              %li
                %a{:href => "http://api.rubyonrails.org/"} Rails API
              %li
                %a{:href => "http://www.ruby-doc.org/core/"} Ruby core
              %li
                %a{:href => "http://www.ruby-doc.org/stdlib/"} Ruby standard library
      #content
        #header
          %h1 Welcome aboard
          %h2 You’re riding Ruby on Rails!
        #about
          %h3
            %a{:href => "rails/info/properties", :onclick => "about(); return false"} About your application’s environment
          #about-content{:style => "display: none"}
        #getting-started
          %h1 Getting started
          %h2 Here’s how to get rolling:
          %ol
            %li
              %h2
                Use
                %code rails generate
                to create your models and controllers
              %p To see all available options, run it without parameters.
            %li
              %h2
                Set up a default route and remove
                %span.filename public/index.html
              %p
                Routes are set up in
                = succeed "." do
                  %span.filename config/routes.rb
            %li
              %h2 Create your database
              %p
                Run
                %code rake db:create
                to create your database. If you're not using SQLite (the default), edit
                %span.filename config/database.yml
                with your username and password.
      #footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Store
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Some Store
          .nav-collapse
            %ul.nav
              %li= link_to "Browse Products", products_path
              %li= link_to "Price List"
              %li= link_to "Contact Us"
              %li= link_to "Cart"
    .container
      .row
        .span9
          = yield
        .span3
          %h2 About Us
          %p Welcome to our store!!!
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/products/_form.html.haml
= form_for @product, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :price, :class => 'control-label'
    .controls
      = f.text_field :price, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn'

app/views/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/products/index.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:price)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.id, product_path(product)
        %td= product.name
        %td= product.price
        %td=l product.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/products/show.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @product.name
%p
  %strong= model_class.human_attribute_name(:price) + ':'
  %br
  = @product.price

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'